// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_ar_X_Y
Rcpp::List get_ar_X_Y(const arma::mat TS_by_node, const int lag_p);
RcppExport SEXP _GraphClustAR_get_ar_X_Y(SEXP TS_by_nodeSEXP, SEXP lag_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type TS_by_node(TS_by_nodeSEXP);
    Rcpp::traits::input_parameter< const int >::type lag_p(lag_pSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ar_X_Y(TS_by_node, lag_p));
    return rcpp_result_gen;
END_RCPP
}
// get_graph_info
Rcpp::List get_graph_info(const arma::mat& adj_w);
RcppExport SEXP _GraphClustAR_get_graph_info(SEXP adj_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adj_w(adj_wSEXP);
    rcpp_result_gen = Rcpp::wrap(get_graph_info(adj_w));
    return rcpp_result_gen;
END_RCPP
}
// update_phi
arma::mat update_phi(const Rcpp::List& X_list, const Rcpp::List& Y_list, arma::mat& phi, arma::mat& nu, arma::mat& theta, const arma::mat& edge_list, const arma::vec& node_degree, const double gamma);
RcppExport SEXP _GraphClustAR_update_phi(SEXP X_listSEXP, SEXP Y_listSEXP, SEXP phiSEXP, SEXP nuSEXP, SEXP thetaSEXP, SEXP edge_listSEXP, SEXP node_degreeSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type edge_list(edge_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type node_degree(node_degreeSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_phi(X_list, Y_list, phi, nu, theta, edge_list, node_degree, gamma));
    return rcpp_result_gen;
END_RCPP
}
// update_nu
arma::mat update_nu(const arma::mat& phi, const arma::mat& theta, const arma::mat& edge_list, const double lambda, const double gamma, const int nu_iter);
RcppExport SEXP _GraphClustAR_update_nu(SEXP phiSEXP, SEXP thetaSEXP, SEXP edge_listSEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP nu_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type edge_list(edge_listSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type nu_iter(nu_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(update_nu(phi, theta, edge_list, lambda, gamma, nu_iter));
    return rcpp_result_gen;
END_RCPP
}
// update_theta
arma::mat update_theta(const arma::mat& phi, const arma::mat& nu, const arma::mat& theta, const arma::mat& edge_list);
RcppExport SEXP _GraphClustAR_update_theta(SEXP phiSEXP, SEXP nuSEXP, SEXP thetaSEXP, SEXP edge_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type edge_list(edge_listSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta(phi, nu, theta, edge_list));
    return rcpp_result_gen;
END_RCPP
}
// GraphClustAR_cpp
Rcpp::List GraphClustAR_cpp(const Rcpp::List& X_list, const Rcpp::List& Y_list, const arma::mat& edge_list, const arma::vec& node_degree, const int ADMM_iter, const int nu_iter, const double lambda, const double gamma, const int lag_p, bool verbose);
RcppExport SEXP _GraphClustAR_GraphClustAR_cpp(SEXP X_listSEXP, SEXP Y_listSEXP, SEXP edge_listSEXP, SEXP node_degreeSEXP, SEXP ADMM_iterSEXP, SEXP nu_iterSEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP lag_pSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type edge_list(edge_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type node_degree(node_degreeSEXP);
    Rcpp::traits::input_parameter< const int >::type ADMM_iter(ADMM_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type nu_iter(nu_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type lag_p(lag_pSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(GraphClustAR_cpp(X_list, Y_list, edge_list, node_degree, ADMM_iter, nu_iter, lambda, gamma, lag_p, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GraphClustAR_get_ar_X_Y", (DL_FUNC) &_GraphClustAR_get_ar_X_Y, 2},
    {"_GraphClustAR_get_graph_info", (DL_FUNC) &_GraphClustAR_get_graph_info, 1},
    {"_GraphClustAR_update_phi", (DL_FUNC) &_GraphClustAR_update_phi, 8},
    {"_GraphClustAR_update_nu", (DL_FUNC) &_GraphClustAR_update_nu, 6},
    {"_GraphClustAR_update_theta", (DL_FUNC) &_GraphClustAR_update_theta, 4},
    {"_GraphClustAR_GraphClustAR_cpp", (DL_FUNC) &_GraphClustAR_GraphClustAR_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_GraphClustAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
