# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build AR(p) design matrices
#'
#' Build AR design matrices given time series data for each node.
#'
#' @param TS_by_node Numeric matrix of size N x n. Each row is the time series for a node.
#' @param lag_p Integer lag p for the AR(p) model.
#'
#' @return A list with two elements:
#' \describe{
#'   \item{X_list}{List of length N; \code{X_list[[i]]} is (n - p) x d design matrix for node i.}
#'   \item{Y_list}{List of length N; \code{Y_list[[i]]} is length (n - p) response vector for node i.}
#' }
#' @examples
#' N = 30 # nodes
#' n = 100 # time points
#' mu = 0
#' sigma = 1
#' phi = 0.8 # AR parameter
#' x_init <- rnorm(N, mean = mu, sd = sigma / sqrt(1 - phi^2))
#' TS_by_node <- matrix(0, nrow = N, ncol = n)
#' TS_by_node[, 1] <- x_init
#' eps <- matrix(rnorm(N * (n-1), 0, 1), nrow = N, ncol = n-1)
#' for (t in 2:n)  TS_by_node[,t] <- mu + phi * (TS_by_node[,t-1] - mu) + eps[,t-1] # AR(1)
#' ar_X_Y <- get_ar_X_Y(TS_by_node, lag_p=4, intercept=FALSE)
#' TS_by_node[1,1:10]         # first 10 time points for node 1
#' ar_X_Y$X_list[[1]][1:6,]   # design matrix with lag_p
#' ar_X_Y$Y_list[[1]][1:6]    # response at lag_p + 1
#' @export
get_ar_X_Y <- function(TS_by_node, lag_p) {
    .Call(`_GraphClustAR_get_ar_X_Y`, TS_by_node, lag_p)
}

#' Get graph information
#'
#' Convert weighted adjacency matrix to (1) edge list and (2) node degrees
#'
#' @param adj_w Numeric matrix (N x N) weighted adjacency matrix. Must be symmetric.
#'
#' @return A list with:
#'   - edge_list: numeric matrix (i, j, w_ij)
#'   - node_degree: integer vector of node degrees
#'
#' @examples
#' # 5-node weighted, symmetric adjacency matrix
#' adj_w <- matrix(0, nrow = 5, ncol = 5)
#' adj_w[1, 2] <- 1.5; adj_w[1, 4] <- 2.0; adj_w[2, 3] <- 0.8; adj_w[4, 5] <- 3.2
#' adj_w <- adj_w + t(adj_w)
#' get_graph_info(adj_w)
#' @export
get_graph_info <- function(adj_w) {
    .Call(`_GraphClustAR_get_graph_info`, adj_w)
}

#' Update phi
#'
#' ADMM update for phi using edge-wise neighbor aggregation.
#' This function will not be export in the final version.
#'
#' @param X_list List of length N; each \code{X_list[[i]]} is (n-p x d) design matrix X_i.
#' @param Y_list List of length N; each \code{Y_list[[i]]} is length n-p response vector Y_i.
#' @param phi N x d matrix of node parameters.
#' @param nu Edge-wise auxiliary variables, E x d matrix.
#' @param theta Edge-wise scaled dual variables, E x d matrix.
#' @param edge_list edge list (E by 3)
#' @param node_degree Numeric vector of length N. This is |B(i)| for each i.
#' @param ts_length length of the time series for each node.
#' @param gamma penalty for the augmentation term
#'
#' @return An N x d matrix with the updated phi.
#' @export
update_phi <- function(X_list, Y_list, phi, nu, theta, edge_list, node_degree, ts_length, gamma) {
    .Call(`_GraphClustAR_update_phi`, X_list, Y_list, phi, nu, theta, edge_list, node_degree, ts_length, gamma)
}

#' Update nu
#'
#' ADMM update for nu using group soft-thresholding.
#' This function will not be export in the final version.
#'
#' @param phi N by d matrix of node parameters (one row per node).
#' @param theta E by d matrix of scaled dual variables.
#' @param edge_list E by 3 matrix. Each row e is (i, j, w_ij)
#' @param lambda GFL penalty parameter.
#' @param gamma penalty parameter for augmentation term.
#'
#' @return Updated nu matrix of size E by d.
#' @export
update_nu <- function(phi, theta, edge_list, lambda, gamma) {
    .Call(`_GraphClustAR_update_nu`, phi, theta, edge_list, lambda, gamma)
}

#' Update theta
#'
#' ADMM update for theta
#' This function will not be export in the final version.
#'
#' @param phi N by d matrix of node parameters.
#' @param nu E by d matrix of auxiliary variables.
#' @param theta E by d matrix of scaled dual variables.
#' @param edge_list E by 3 matrix. Each row e is (i, j, w_ij)
#'
#' @return Updated nu matrix of size E by p.
#' @export
update_theta <- function(phi, nu, theta, edge_list) {
    .Call(`_GraphClustAR_update_theta`, phi, nu, theta, edge_list)
}

#' ADMM for GraphClustAR
#'
#' ADMM for GraphClustAR (cpp version)
#' This function will not be export in the final version.
#'
#' @param X_list List of length N; each \code{X_list[[i]]} is (n-p x p) design matrix X_i.
#' @param Y_list List of length N; each \code{Y_list[[i]]} is length n-p response vector Y_i.
#' @param edge_list edge list (E by 3)
#' @param node_degree Numeric vector of length N. This is |B(i)| for each i.
#' @param lag_p Integer lag p for the AR(p) model.
#' @param ts_length length of the time series for each node.
#' @param ADMM_iter ADMM iteration.
#' @param lambda GFL penalty parameter.
#' @param gamma penalty for the augmentation term.
#' @param phi_tol ADMM stopping criteria based on phi.
#' @param update_gamma If TRUE, gamma is updated with schedule.
#' @param verbose If TRUE, print info during learning.
#'
#' @return An N x d matrix with the updated phi.
#' @export
GraphClustARp_cpp <- function(X_list, Y_list, edge_list, node_degree, lag_p, ts_length, ADMM_iter, lambda, gamma, phi_tol, update_gamma, verbose) {
    .Call(`_GraphClustAR_GraphClustARp_cpp`, X_list, Y_list, edge_list, node_degree, lag_p, ts_length, ADMM_iter, lambda, gamma, phi_tol, update_gamma, verbose)
}

#' Calculate log-likelihood for AR(p) model
#'
#' @param X_list List of AR design matrices.
#' @param Y_list List of response vectors.
#' @param phi_hat Estimated AR coefficients (N x (p+1)).
#' @param n_ts Time series length.
#'
#' @return log-likelihood.
#' @export
cal_ar_loglik <- function(X_list, Y_list, phi_hat, n_ts) {
    .Call(`_GraphClustAR_cal_ar_loglik`, X_list, Y_list, phi_hat, n_ts)
}

#' Calculate BIC for GraphClustAR AR model
#'
#' Calculates the Bayesian information criterion (BIC)
#'
#' @param X_list List of AR design matrices.
#' @param Y_list List of response vectors.
#' @param phi_hat Estimated AR coefficients (N x (p+1)).
#' @param K_hat Integer. Number of detected clusters.
#' @param n_ts Time series length.
#'
#' @return BIC
#'
#' @export
cal_ar_BIC <- function(X_list, Y_list, phi_hat, K_hat, n_ts) {
    .Call(`_GraphClustAR_cal_ar_BIC`, X_list, Y_list, phi_hat, K_hat, n_ts)
}

